# TITLE

In [17]:
# Libraries
import pandas as pd
from utils.download import download_week
import os

In [18]:
# Load TidyTuesday week
if not os.path.isdir("data"):
    download_week(2026, 32)

In [19]:
# Load data
pel = pd.read_csv("data/palomar_emission_lines.csv")  # Palomar Emission Lines
ps = pd.read_csv("data/palomar_survey.csv")  # Palomar Survey

## Head of Palomar Emission Lines

In [20]:
pel.head()

,galaxy_name,h_gamma,h_beta,oiii_5007,oi_6300,nii_6583,sii_6716,sii_6731
0,IC 10,0.03,0.08,0.35,0.006,0.04,0.03,0.03
1,IC 239,NaN,1.47,1.47,0.590,0.59,1.00,1.00
2,IC 342,0.03,0.13,0.01,0.007,0.45,0.10,0.12
3,IC 356,NaN,0.10,0.24,0.110,1.68,0.51,0.43
4,IC 467,NaN,0.17,0.07,0.058,0.44,0.28,0.20

## Head of Palomar Survey

In [21]:
ps.head()

,galaxy_name,hubble_type,b_magnitude,helio_velocity_km_s,ra_j2000,dec_j2000,ha_hb_ratio,internal_reddening_ebv,sii_density_ratio,electron_density_cm3,log_oiii_hb,log_oi_ha,log_nii_ha,log_sii_ha,spectral_class,activity_type,activity_subtype,classification_confidence,velocity_dispersion_km_s,velocity_dispersion_error
0,NGC 7814,S(ab),11.3,1042,00 03 14.9,+16 08 42,1.52,0.00,NaN,NaN,1.00,0.600,0.76,1.96,L2::,LINER,2.0,very uncertain,172.3,7.7
1,NGC 7817,Sbc:(spindle),12.4,2157,00 03 58.1,+20 45 06,5.27,0.62,1.38,62.0,1.56,0.014,0.39,0.22,H,H II,NaN,confident,66.7,8.4
2,NGC 63,S pec,12.3,1172,00 17 45.7,+11 26 58,5.65,0.69,1.12,360.0,0.43,0.016,0.49,0.33,H,H II,NaN,confident,25.6,8.8
3,IC 10,Im? IV,11.7,-342,00 20 24.1,+59 17 33,5.18,0.60,1.32,115.0,4.35,0.006,0.04,0.06,H,H II,NaN,confident,35.5,16.6
4,NGC 147,dE5,10.3,-160,00 33 12.2,+48 30 20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,5.0

## What is the shapee of the data?

In [22]:
print(f"pel.csv has {pel.shape[0]} rows and {pel.shape[1]} columns.")
print(f"ps.csv has {ps.shape[0]} rows and {ps.shape[1]} columns.")

pel.csv has 418 rows and 8 columns.
ps.csv has 486 rows and 20 columns.

## Any missing values for the palomar emission lines?

In [23]:
print(pel.isna().sum())

galaxy_name      0
h_gamma        185
h_beta           7
oiii_5007        7
oi_6300          0
nii_6583         0
sii_6716         2
sii_6731         2
dtype: int64

## Any missing values for the palomar survey?

In [24]:
print(ps.isna().sum())

galaxy_name                    0
hubble_type                    0
b_magnitude                    0
helio_velocity_km_s            0
ra_j2000                       0
dec_j2000                      0
ha_hb_ratio                   87
internal_reddening_ebv        86
sii_density_ratio             89
electron_density_cm3          89
log_oiii_hb                   78
log_oi_ha                     71
log_nii_ha                    71
log_sii_ha                    72
spectral_class                72
activity_type                 71
activity_subtype             271
classification_confidence     71
velocity_dispersion_km_s       5
velocity_dispersion_error     17
dtype: int64